name: Minimal CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install core dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib numpy sympy pytest
    
    - name: Test imports
      run: |
        PYTHONPATH=src python -c "from xi import XiOscillator, XiSymbolic, xi_operator; print('All imports successful')"
    
    - name: Run tests
      run: |
        PYTHONPATH=src python -m pytest tests/ -v --tb=short
    
    - name: Test basic functionality
      run: |
        python test_basic.py

  test-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install core dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib numpy sympy pytest
    
    - name: Test imports
      run: |
        $env:PYTHONPATH="src"; python -c "from xi import XiOscillator, XiSymbolic, xi_operator; print('All imports successful')"
    
    - name: Run tests
      run: |
        $env:PYTHONPATH="src"; python -m pytest tests/ -v --tb=short
    
    - name: Test basic functionality
      run: |
        python test_basic.py