name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quick-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    - name: Test imports
      run: |
        python -c "import sys; sys.path.insert(0, 'src'); from xi import XiOscillator, XiSymbolic, xi_operator; print('✓ Imports successful')"
    
    - name: Run basic test
      run: |
        python test_basic.py
    
    - name: Run pytest
      run: |
        python -m pytest tests/ -v --tb=short
    
    - name: Test CLI
      run: |
        python src/cli.py demo
      continue-on-error: true

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11']  # Reduced matrix for faster testing

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    - name: Test imports
      run: |
        python -c "import sys; sys.path.insert(0, 'src'); from xi import XiOscillator; print('✓ Core imports work')"
    
    - name: Run tests
      run: |
        python -m pytest tests/ -v --tb=short